#
# Makefile for LITMUS^RT
#

obj-y     = sched_plugin.o litmus.o sched_trace.o \
	    edf_common.o \
            sched_gsn_edf.o sched_psn_edf.o litmus_sem.o \
	    trace.o ft_event.o rt_domain.o fdso.o
